language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
install:
    - npm install xvfb-maybe
    - npm install
script:
  - npm run build
  - xvfb-maybe npm test