sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - xvfb
      - google-chrome-stable

language: node_js

node_js:
  - "6"
  - "7"

cache:
  directories:
    - node_modules

before_script:
  - npm run build
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - npm test
