language: node_js
node_js:
  - '7'
os: linux
sudo: required
dist: trusty
cache:
  apt: true
  directories:
    - node_modules
before_install:
  - sudo apt-get update
addons:
  apt:
    packages:
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
install:
    - npm install -g xvfb-maybe
    - npm install
before_script:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 -extension RANDR &
script:
  - npm run build
  - xvfb-maybe npm test