language: node_js
node_js:
  - '7'
os: linux
sudo: required
dist: trusty
cache:
  apt: true
  directories:
    - node_modules
before_install:
  - sudo apt-get update
addons:
  apt:
    packages:
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
install:
    - npm install
before_script:
    - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
    - sleep 3
script:
  - npm run build
  - xvfb-run -a npm test