language: node_js
node_js:
  - '7'
install:
    - npm install xvfb-maybe
    - npm install
before_script:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 -extension RANDR &
script:
  - npm run build
  - npm test
os: linux
dist: trusty
sudo: required