language: node_js
node_js:
  - '7'
os: linux
dist: trusty
sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev

install:
    - npm install -g xvfb-maybe
    - npm install
before_script:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 -extension RANDR &
script:
  - npm run build
  - xvfb-maybe npm test