sudo: required
dist: trusty
language: node_js
node_js:
  - '7'
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - export DISPLAY=:99.0
  
  - Xvfb :21 -screen 0 1024x768x24 +extension RANDR &
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - npm run build
  - npm test