sudo: false
dist: trusty
addons:
  apt:
    packages:
      - xvfb

language: node_js

node_js:
  - "6"
  - "7"

cache:
  directories:
    - node_modules

before_script:
  - npm run build
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - npm test
